import { Layout } from "@/components/layout";
import "@/styles/globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
	colorScheme: " dark",
  other: {
    'darkreader-lock': '',
    'theme-color': '#000000',
    'color-scheme': 'dark',
    
  },

};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
