import { Layout } from "@/components/layout";
import "@/styles/globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
	themeColor: "#000000", // Cor escura do seu tema
	other: {
		"darkreader-lock": "",
		"dark-theme": "true",
		"color-scheme": "dark",
	}
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" data-theme="dark">
			<head>
				<meta name="darkreader-lock" content="" />
				<meta name="dark-theme" content="true" />
				<style
					dangerouslySetInnerHTML={{
						__html: `
							html { color-scheme: dark !important; }
							html[data-darkreader-mode] { 
								--darkreader-inline-bgcolor: transparent !important;
								--darkreader-inline-color: inherit !important;
							}
						`
					}}
				/>
			</head>
			<body>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}